"""add db_type to connections

Revision ID: 2eb501eb1f71
Revises: e1e14fe41eae
Create Date: 2026-07-29 00:49:56.027578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb501eb1f71'
down_revision: Union[str, None] = 'e1e14fe41eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('db_connections', sa.Column('db_type', sa.String(length=20), nullable=False))
    op.add_column('db_connections', sa.Column('db_type', sa.String(length=20), nullable=False, server_default='postgres'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_connections', 'db_type')
    # ### end Alembic commands ###
